In [2]:
# import libraries and data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Loading the datasets
results = pd.read_csv('../data/results.csv',encoding = "utf-8")
status = pd.read_csv('../data/status.csv',encoding = "utf-8")


# Combining datasets for a full view
merged_data = pd.merge(results, status, on='statusId')


# View this data
merged_data.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,status
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1,Finished
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1,Finished
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1,Finished
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1,Finished
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1,Finished

In [3]:
# Counting n(Finish)
finishes = merged_data[merged_data['status'] == 'Finished'].shape[0]

# Counting n(Total Race Starts)
total_races = merged_data.shape[0]

In [4]:
# Calculating the probability, i.e., P(Finish)
prob_finish = finishes / total_races
print(f"Zooming in, the probability of finishing a race is {prob_finish:.2f}. Vroom vroom!")

Zooming in, the probability of finishing a race is 0.28. Vroom vroom!

In [5]:
# Calculate the frequency of each status
status_counts = merged_data['status'].value_counts()

# Calculate the probability of each status by dividing the count by the total number of entries
probabilities = status_counts / total_races

# Print the probabilities for each status
print("Probabilities for each status:")
print(probabilities)

# Sum up the probabilities to check if they add up to 1
total_probability = probabilities.sum()
print("\nTotal Probability:", total_probability)

Probabilities for each status:
status
Finished          0.279488
+1 Lap            0.149160
Engine            0.077044
+2 Laps           0.061039
Accident          0.040145
                    ...
Launch control    0.000038
Tyre puncture     0.000038
+26 Laps          0.000038
CV joint          0.000038
Crankshaft        0.000038
Name: count, Length: 137, dtype: float64

Total Probability: 1.0